core/urls.py
from django.urls import path
from . import views



app_name = 'core'

urlpatterns = [
    
    path('', views.main, name='main'),
    path('short-sleeves/', views.short_sleeves, name='short_sleeves'),
    path('long-sleeves/', views.long_sleeves, name='long_sleeves'),
    path('pants/', views.pants, name='pants'),
    path('shorts/', views.shorts, name='shorts'),
    path('shoes/', views.shoes, name='shoes'),
    path('accessories/', views.accessories, name='accessories'),
    path('sweaters/', views.sweaters, name='sweaters'),
    path('jackets/', views.jackets, name='jackets'),
    path('tracksuits/', views.tracksuits, name='tracksuits'),
    path('budget/', views.budget, name='budget'),
    path('watches/', views.watches, name='watches'),
    path('tech/', views.tech, name='tech'),
]

pandabuy/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import main
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]      

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'core/index.html')

def short_sleeves(request):
    product_data = [
        {"name": "Polo Shirts", "image": "short_sleeves_images/image1.png", "url": "https://pandabuy.allapp.link/co5bmbnm8ngrr7t9e570"},  
        {"name": "Bape Shirts","image": "short_sleeves_images/image2.jpg", "url": "https://pandabuy.allapp.link/co5bmt0gpf6pm1sj9ocg"},
        {"name": "Hellstar Shirts", "image": "short_sleeves_images/image3.webp", "url": "https://pandabuy.allapp.link/co5bn2fm8ngrr7t9e5lg"},
        {"name": "ESSENTIALS Shirts", "image": "short_sleeves_images/image4.avif", "url": "https://pandabuy.allapp.link/co5bnkprogtuqkqe2tj0"},
        {"name": "ASSC Shirts", "image": "short_sleeves_images/image5.avif", "url": "https://pandabuy.allapp.link/co5bntnm8ngrr7t9e67g"},
        

        {"name": "Vlone Shirts", "image": "short_sleeves_images/image6.jpg", "url": "https://pandabuy.allapp.link/co5bo5progtuqkqe2u00"},  
        {"name": "Sicko X Joy Shirts","image": "short_sleeves_images/image7.avif", "url": "https://pandabuy.allapp.link/co5bp78gpf6pm1sj9qe0"},
        {"name": "Blank Shirts", "image": "short_sleeves_images/image8.avif", "url": "https://pandabuy.allapp.link/co5bpb1rogtuqkqe2v2g"},
        {"name": "Yeezus Tour Merch Shirts", "image": "short_sleeves_images/image9.jpg", "url": "https://pandabuy.allapp.link/co5bphogpf6pm1sj9qo0"},
        {"name": "Jacquemes Artichoke Shirts", "image": "short_sleeves_images/image10.jpg", "url": "https://pandabuy.allapp.link/co5bpn1rogtuqkqe2vf0"},

        {"name": "Narcissict Merch", "image": "short_sleeves_images/image11.jpg", "url": "https://pandabuy.allapp.link/co5bqk9rogtuqkqe30e0"},   
        {"name": "Fat Tub Of Lard Shirts ","image": "short_sleeves_images/image12.avif", "url": "https://pandabuy.allapp.link/co5bqtvm8ngrr7t9e93g"},
        {"name": "Balenciaga Misplaced Shirt ", "image": "short_sleeves_images/image13.jpg", "url": "https://pandabuy.allapp.link/co5brb9rogtuqkqe3120"},
        {"name": "Vetements I did Nothing Shirt", "image": "short_sleeves_images/image14.avif", "url": "https://pandabuy.allapp.link/co5brqfm8ngrr7t9e9l0"},
        {"name": "30+ Travis Scot Merch ", "image": "short_sleeves_images/image15.avif", "url": "https://pandabuy.allapp.link/co5bs17m8ngrr7t9e9r0"},

        {"name": "OnlyFans Shirts", "image": "short_sleeves_images/image16.avif", "url": "https://pandabuy.allapp.link/co5bsevm8ngrr7t9ea80"}, 
        {"name": "Two piece Shirts ","image": "short_sleeves_images/image17.avif", "url": "https://pandabuy.allapp.link/co5bsl1rogtuqkqe31ug"},
        {"name": "Balenciaga Sporty B Shrunk Tee", "image": "short_sleeves_images/image18.jpg", "url": "https://pandabuy.allapp.link/co5bsr0gpf6pm1sj9t80"},
        {"name": "Balenciaga x Adidas Shirts", "image": "short_sleeves_images/image19.jpg", "url": "https://pandabuy.allapp.link/co5bvdprogtuqkqe34f0"},
        {"name": "Carti WLR Vampire Shirt White", "image": "short_sleeves_images/image20.avif", "url": "https://pandabuy.allapp.link/co5bvkvm8ngrr7t9ecug"},

        {"name": "Carti WLR Hell Merch ", "image": "short_sleeves_images/image21.avif", "url": "https://pandabuy.allapp.link/co5bvsogpf6pm1sj9vk0"},   
        {"name": "Corteiz Shirts ","image": "short_sleeves_images/image22.jpg", "url": "https://pandabuy.allapp.link/co5c068gpf6pm1sj9vu0"},
        {"name":"Carti x CPFM Merch White ", "image": "short_sleeves_images/image23.avif", "url": "https://pandabuy.allapp.link/co5c0l1rogtuqkqe35b0"},
        {"name": "Chrome Heart Cross Shirt", "image": "short_sleeves_images/image24.jpg", "url": "https://pandabuy.allapp.link/co5c0s1rogtuqkqe35l0"},
        {"name": "Dennis Rodman Tee ", "image": "short_sleeves_images/image25.avif", "url": "https://pandabuy.allapp.link/co5c0vvm8ngrr7t9ee30"},

        {"name": "Golf Wang Shirts ", "image": "short_sleeves_images/image26.avif", "url": "https://pandabuy.allapp.link/co5c2i7m8ngrr7t9ef60"},  
        {"name": "Frank Ocean Blonded Tee ","image": "short_sleeves_images/image27.jpg", "url": "https://pandabuy.allapp.link/co5c2oogpf6pm1sja250"},
        {"name":"Gallery Dept Alone in Silence Shirt ", "image": "short_sleeves_images/image28.jpg", "url": "https://pandabuy.allapp.link/co5c2uprogtuqkqe37d0"},
        {"name": "Fragment Clot Tee (2006)", "image": "short_sleeves_images/image29.jpg", "url": "https://weidian.info/jjxh6"},#dont work - wrong link
        {"name": "Fuck Me? Fuck You! Number Nine Shirt ", "image": "short_sleeves_images/image30.avif", "url": "https://pandabuy.allapp.link/co5f29ggpf6pm1sjcnk0"},

        {"name": "Gallery Dept Middle Finger Tee ", "image": "short_sleeves_images/image31.avif", "url": "https://pandabuy.allapp.link/co5f47fm8ngrr7t9hah0"},  
        {"name": "Gallery DEPT Hollywood T-shirt ","image": "short_sleeves_images/image32.jpg", "url": "https://pandabuy.allapp.link/co5f4e8gpf6pm1sjcpm0"},
        {"name":"Gothic Slogan Number Nine Shirt ", "image": "short_sleeves_images/image33.avif", "url": "https://pandabuy.allapp.link/co5f59nm8ngrr7t9hbjg"},#dont work - wrong link
        {"name": "Corteiz Grass T-shirts", "image": "short_sleeves_images/image34.jpg", "url": "https://pandabuy.allapp.link/co5f5jnm8ngrr7t9hbt0"},
        {"name": "FG T-shirts ", "image": "short_sleeves_images/image35.jpg", "url": "https://pandabuy.allapp.link/co5f5qnm8ngrr7t9hc60"},
        
        {"name": "Hellstar Grateful Dead Tee ", "image": "short_sleeves_images/image36.jpg", "url": "https://pandabuy.allapp.link/co5fha0gpf6pm1sjd5gg"},  
        {"name": "CPFM Hawaiian Shirt ","image": "short_sleeves_images/image37.avif", "url": "https://pandabuy.allapp.link/co5fhfvm8ngrr7t9hms0"},
        {"name":"Kapital Ringer Tee ", "image": "short_sleeves_images/image38.avif", "url": "https://pandabuy.allapp.link/co5fhonm8ngrr7t9hn60"},
        {"name": "House of Errors T-Shirt", "image": "short_sleeves_images/image39.avif", "url": "https://pandabuy.allapp.link/co5fi08gpf6pm1sjd640"},
        {"name": "Grateful Dead Shirt", "image": "short_sleeves_images/image40.jpg", "url": "https://pandabuy.allapp.link/co5fibprogtuqkqe6b9g"},

        {"name": "Dior Oblique Print Polo Shirts", "image": "short_sleeves_images/image41.jpg", "url": "https://pandabuy.allapp.link/co5fikhrogtuqkqe6bg0"},   
        {"name": "Joy Sicko Tee ","image": "short_sleeves_images/image42.avif", "url": "https://pandabuy.allapp.link/co5fjp0gpf6pm1sjd7m0"},
        {"name":"Playboi Carti Falling in Reverse WLR Shirt", "image": "short_sleeves_images/image43.avif", "url": "https://pandabuy.allapp.link/co5fju7m8ngrr7t9hp80"},
        {"name": "Led Zeppelin Number Nine Shirt ", "image": "short_sleeves_images/image44.avif", "url": "https://pandabuy.allapp.link/co5fkn9rogtuqkqe6d5g"},
        {"name": "Playboi Carti WLR Merch", "image": "short_sleeves_images/image45.avif", "url": "https://pandabuy.allapp.link/co5fkvhrogtuqkqe6de0"},

        {"name": "10+ Vintage Rapper Graphic Tees", "image": "short_sleeves_images/image46.avif", "url": "https://pandabuy.allapp.link/co5fd57m8ngrr7t9hj6g"},   
        {"name": "Trapstar Jerseys ","image": "short_sleeves_images/image47.jpg", "url": "https://pandabuy.allapp.link/co5ffiprogtuqkqe693g"},
        {"name":"Number Nine 3 Mickey Shirts", "image": "short_sleeves_images/image48.avif", "url": "https://pandabuy.allapp.link/co5fg0ggpf6pm1sjd4jg"},
        {"name": "Prada Dress Shirts", "image": "short_sleeves_images/image49.avif", "url": "https://pandabuy.allapp.link/co5fg8hrogtuqkqe69ig"},
        {"name": "Rick Owens DRKR Tee", "image": "short_sleeves_images/image50.jpg", "url": "https://pandabuy.allapp.link/co5fguprogtuqkqe6a5g"},

        {"name": "Kurt Cobain Number Nine ", "image": "short_sleeves_images/image51.avif", "url": "https://pandabuy.allapp.link/co5fbkggpf6pm1sjd07g"},  
        {"name": "Nirvana Shirt","image": "short_sleeves_images/image52.avif", "url": "https://pandabuy.allapp.link/co5fbsfm8ngrr7t9hhlg"},
        {"name":"Loved Gun Number Nine T Shirt", "image": "short_sleeves_images/image53.avif", "url": "https://pandabuy.allapp.link/co5fceprogtuqkqe65vg"},
        {"name": "Ken Car$on Teen X Merch ", "image": "short_sleeves_images/image54.avif", "url": "https://pandabuy.allapp.link/co5fcm0gpf6pm1sjd19g"},
        {"name": "Narcissist Merch", "image": "short_sleeves_images/image55.avif", "url": "https://pandabuy.allapp.link/co5fct9rogtuqkqe66d0"},

        {"name": "Nirvana Vintage Shirts", "image": "short_sleeves_images/image56.jpg", "url": "https://pandabuy.allapp.link/co5f8lfm8ngrr7t9het0"},  
        {"name": "Undercover x CDG Shirt","image": "short_sleeves_images/image57.avif", "url": "https://pandabuy.allapp.link/co5f8shrogtuqkqe62n0"},
        {"name":"Undercover Scab Scorpion T-Shirt", "image": "short_sleeves_images/image58.avif", "url": "https://pandabuy.allapp.link/co5f95fm8ngrr7t9hf9g"},
        {"name": "Mood Swings T-Shirts", "image": "short_sleeves_images/image59.avif", "url": "https://pandabuy.allapp.link/co5f9fogpf6pm1sjcuf0"},
        {"name": "Rick Owens Fog Machine T Shirts", "image": "short_sleeves_images/image60.jpg", "url": "https://pandabuy.allapp.link/co5favhrogtuqkqe64ig"},

        {"name": "Playboi Carti Anime Shirt White ", "image": "short_sleeves_images/image61.avif", "url": "https://pandabuy.allapp.link/co5f7efm8ngrr7t9hdmg"}, 
        {"name": "Eyeball Vintage Tee ","image": "short_sleeves_images/image62.jpg", "url": "https://pandabuy.allapp.link/co5f7l1rogtuqkqe61gg"},
        {"name":"Kapital Two Tone Shirts", "image": "short_sleeves_images/image63.avif", "url": "https://pandabuy.allapp.link/co5f7sfm8ngrr7t9he50"},
        {"name": "Carti WLR Hell Merch White ", "image": "short_sleeves_images/image64.avif", "url": "https://pandabuy.allapp.link/co5f850gpf6pm1sjct7g"},
        {"name": "Saint Michael Virgin Mary Tee", "image": "short_sleeves_images/image65.avif", "url": "https://pandabuy.allapp.link/co5f8bhrogtuqkqe6270"},

core/templates/core/accessories.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accessories</title>
    <style>
        /* Reset CSS */
        body {
            background-color: #f8f9fa; /* Light Gray */
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }

        /* Banner Styles */
        .banner {
            background-color: #343a40; /* Dark Gray */
            color: #ffffff;
            padding: 20px;
            text-align: center;
            font-size: 24px;
            font-weight: bold;
        }

        /* Menu Styles */
        .menu {
            text-align: center;
            margin-bottom: 20px;
        }

        .menu ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        .menu li {
            display: inline-block;
            margin-right: 20px;
            position: relative;
        }

        .menu a {
            color: #007bff; /* Blue */
            text-decoration: none;
            font-size: 18px;
        }

        .menu a:hover {
            text-decoration: underline;
        }

        /* Tooltip Styles */
        .tooltip {
            position: absolute;
            bottom: 100%;
            left: 50%;
            transform: translateX(-50%);
            background-color: #212529; /* Dark Gray */
            color: #ffffff;
            text-align: center;
            border-radius: 6px;
            padding: 5px;
            visibility: hidden;
            opacity: 0;
            transition: opacity 0.3s, visibility 0s linear 0.3s;
        }

        .menu li:hover .tooltip {
            visibility: visible;
            opacity: 1;
            transition: opacity 0.3s;
        }

        /* Paragraph Styles */
        .content {
            padding: 20px;
            text-align: center;
        }

        .content p {
            font-size: 16px;
            line-height: 1.6;
            margin-bottom: 20px;
            color: #495057; /* Dark Gray */
        }

        /* Button Container Styles */
        .button-container {
            text-align: center;
            margin-top: 50px;
        }

        /* Button Styles */
        .button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            border: none;
            border-radius: 5px;
            background-color: #007bff; /* Blue */
            color: white;
            transition: background-color 0.3s;
        }

        .button:hover {
            background-color: #0056b3; /* Darker Blue */
        }



        #affiliateButton {
            background-color: #ff4500; /* Affiliate color */
        }

        .grid-container {
            display: grid;
            grid-template-columns: repeat(5, 1fr); /* 5 columns */
            gap: 10px; /* gap between items */
            justify-items: center; /* center items horizontally */
        }

        .grid-item {
            text-align: center;
            width: 100%; /* Ensures each item takes the full width of its grid cell */
        }

        .grid-item img {
            width: 100%; /* Ensures the image fills its container */
            height: 200px; /* Set a fixed height for all images */
            object-fit: cover; /* Maintain aspect ratio while covering the area */
            transition: transform 0.3s ease; /* smooth transition for zoom effect */
        }

        .grid-item img:hover {
            transform: scale(1.1); /* zoom in effect on hover */
        }
    </style>
</head>
<body>
    <div class="banner">
        <a href="https://pandabuy.allapp.link/co444r9rogtreqrjiqa0">Click Link To Get 5% Discount</a>
    </div>

    <!-- Menu -->
    <div class="menu">
        <ul>
            <li><a href="{% url 'core:main' %}" style="color: #dc3545;">Home</a><span class="tooltip">Return to the homepage</span></li>
            <li><a href="{% url 'core:short_sleeves' %}" style="color: #ffc107;">Short Sleeves</a><span class="tooltip">Short Sleeves</span></li>
            <li><a href="{% url 'core:long_sleeves' %}" style="color: #28a745;">Long Sleeves</a><span class="tooltip">Long Sleeves</span></li>
            <li><a href="{% url 'core:pants' %}" style="color: #007bff;">Pants</a><span class="tooltip">Pants</span></li>
            <li><a href="{% url 'core:shorts' %}" style="color: #6610f2;">Shorts</a><span class="tooltip">Shorts</span></li>
            <li><a href="{% url 'core:shoes' %}" style="color: #007bff;">Shoes</a><span class="tooltip">Shoes</span></li>
            <li><a href="{% url 'core:accessories' %}" style="color: #6c757d;">Accessories</a><span class="tooltip">Accessories</span></li>
            <li><a href="{% url 'core:sweaters' %}" style="color: #007bff;">Sweaters</a><span class="tooltip">Sweaters</span></li>
            <li><a href="{% url 'core:jackets' %}" style="color: #17a2b8;">Jackets</a><span class="tooltip">Jackets</span></li>
            <li><a href="{% url 'core:tracksuits' %}" style="color: #ffc107;">Tracksuits</a><span class="tooltip">Tracksuits</span></li>
            <li><a href="{% url 'core:budget' %}" style="color: #007bff;">Budget</a><span class="tooltip">Budget</span></li>
            <li><a href="{% url 'core:watches' %}" style="color: #e83e8c;">Watches</a><span class="tooltip">Watches</span></li>
            <li><a href="{% url 'core:tech' %}" style="color: #007bff;">Tech</a><span class="tooltip">Tech</span></li>
        </ul>

        
    </div>

    <!-- Grid Container -->
    <div class="grid-container">
        {% load static %}
        {% for product in product_data %}
        <div class="grid-item">
            <a href="{{ product.url }}">
                <img src="{% static product.image %}" alt="{{ product.name }}">
            </a>
            <p><a href="{{ product.url }}">{{ product.name }}</a></p>
        </div>
        {% endfor %}


    
</body>
</html>

core/templates/core/budget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Budget</title>
    <style>
        /* Reset CSS */
        body {
            background-color: #f8f9fa; /* Light Gray */
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }

        /* Banner Styles */
        .banner {
            background-color: #343a40; /* Dark Gray */
            color: #ffffff;
            padding: 20px;
            text-align: center;
            font-size: 24px;
            font-weight: bold;
        }

        /* Menu Styles */
        .menu {
            text-align: center;
            margin-bottom: 20px;
        }

        .menu ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        .menu li {
            display: inline-block;
            margin-right: 20px;
            position: relative;
        }

        .menu a {
            color: #007bff; /* Blue */
            text-decoration: none;
            font-size: 18px;
        }

        .menu a:hover {
            text-decoration: underline;
        }

        /* Tooltip Styles */
        .tooltip {
            position: absolute;
            bottom: 100%;
            left: 50%;
            transform: translateX(-50%);
            background-color: #212529; /* Dark Gray */
            color: #ffffff;
            text-align: center;
            border-radius: 6px;
            padding: 5px;
            visibility: hidden;
            opacity: 0;
            transition: opacity 0.3s, visibility 0s linear 0.3s;
        }

        .menu li:hover .tooltip {
            visibility: visible;
            opacity: 1;
            transition: opacity 0.3s;
        }

        /* Paragraph Styles */
        .content {
            padding: 20px;
            text-align: center;
        }

        .content p {
            font-size: 16px;
            line-height: 1.6;
            margin-bottom: 20px;
            color: #495057; /* Dark Gray */
        }

        /* Button Container Styles */
        .button-container {
            text-align: center;
            margin-top: 50px;
        }

        /* Button Styles */
        .button {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            border: none;
            border-radius: 5px;
            background-color: #007bff; /* Blue */
            color: white;
            transition: background-color 0.3s;
        }

        .button:hover {
            background-color: #0056b3; /* Darker Blue */
        }



        #affiliateButton {
            background-color: #ff4500; /* Affiliate color */
        }

        .grid-container {
            display: grid;
            grid-template-columns: repeat(5, 1fr); /* 5 columns */
            gap: 10px; /* gap between items */
            justify-items: center; /* center items horizontally */
        }

        .grid-item {
            text-align: center;
            width: 100%; /* Ensures each item takes the full width of its grid cell */
        }

        .grid-item img {
            width: 100%; /* Ensures the image fills its container */
            height: 200px; /* Set a fixed height for all images */
            object-fit: cover; /* Maintain aspect ratio while covering the area */
            transition: transform 0.3s ease; /* smooth transition for zoom effect */
        }

        .grid-item img:hover {
            transform: scale(1.1); /* zoom in effect on hover */
        }
    </style>
</head>
<body>
    <div class="banner">
        <a href="https://pandabuy.allapp.link/co444r9rogtreqrjiqa0"> Click Link To Get 5% Discount</a>
    </div>

    <!-- Menu -->
    <div class="menu">
        <ul>
            <li><a href="{% url 'core:main' %}" style="color: #dc3545;">Home</a><span class="tooltip">Return to the homepage</span></li>
            <li><a href="{% url 'core:short_sleeves' %}" style="color: #ffc107;">Short Sleeves</a><span class="tooltip">Short Sleeves</span></li>
            <li><a href="{% url 'core:long_sleeves' %}" style="color: #28a745;">Long Sleeves</a><span class="tooltip">Long Sleeves</span></li>
            <li><a href="{% url 'core:pants' %}" style="color: #007bff;">Pants</a><span class="tooltip">Pants</span></li>
            <li><a href="{% url 'core:shorts' %}" style="color: #6610f2;">Shorts</a><span class="tooltip">Shorts</span></li>
            <li><a href="{% url 'core:shoes' %}" style="color: #007bff;">Shoes</a><span class="tooltip">Shoes</span></li>
            <li><a href="{% url 'core:accessories' %}" style="color: #6c757d;">Accessories</a><span class="tooltip">Accessories</span></li>
            <li><a href="{% url 'core:sweaters' %}" style="color: #007bff;">Sweaters</a><span class="tooltip">Sweaters</span></li>
            <li><a href="{% url 'core:jackets' %}" style="color: #17a2b8;">Jackets</a><span class="tooltip">Jackets</span></li>
            <li><a href="{% url 'core:tracksuits' %}" style="color: #ffc107;">Tracksuits</a><span class="tooltip">Tracksuits</span></li>
            <li><a href="{% url 'core:budget' %}" style="color: #007bff;">Budget</a><span class="tooltip">Budget</span></li>
            <li><a href="{% url 'core:watches' %}" style="color: #e83e8c;">Watches</a><span class="tooltip">Watches</span></li>
            <li><a href="{% url 'core:tech' %}" style="color: #007bff;">Tech</a><span class="tooltip">Tech</span></li>
        </ul>
    </div>


    <!-- Grid Container -->
    <div class="grid-container">
        {% load static %}
        {% for product in product_data %}
        <div class="grid-item">
            <a href="{{ product.url }}">
                <img src="{% static product.image %}" alt="{{ product.name }}">
            </a>
            <p><a href="{{ product.url }}">{{ product.name }}</a></p>
        </div>
        {% endfor %}


    
</body>
</html>